image: node:16.13.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - unit-test

Unit Test:
  stage: unit-test
  tags:
    - node
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
    - yarn test run
