image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - install
  - unit-test

Install:
  stage: install
  tags:
    - node
  before_script: 
    - yarn config set cache-folder .yarn
  script:
    - yarn install 

Unit Test:
  stage: unit-test
  tags:
    - node
  script:
    - yarn test run
