image: cypress/base:16

cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install
  - yarn config set cache-folder .yarn
  - yarn install 

stages:
  - lint
  - test
  - build
  - deploy

Linting:
  stage: lint
  script:
    - yarn lint

Unit Test:
  stage: test
  script:
    - yarn test run

# TODO: Make e2e tests more stable
# E2E Test:
#   stage: test
#   script:
#     - yarn start & yarn test:e2e

Build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - 'dist'

Deploy Prod:
  stage: deploy
  script:
    - yarn deploy
  only:
    - feature/cicd