image: cypress/base:16

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - setup
  - lint
  - test
  - build
  - deploy

Setup:
  stage: setup
  script:
    - yarn install

Linting:
  stage: lint
  script:
    - yarn lint

Unit Test:
  stage: test
  script:
    - yarn test run

# TODO: Make e2e tests more stable
# E2E Test:
#   stage: test
#   script:
#     - yarn start & yarn test:e2e

Build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - 'dist'

Deploy Prod:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - yarn deploy
  only:
    - feature/cicd